---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: policyfile_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.8.1

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    provisioner:
      named_run_list: default
    verifier:
      inspec_tests:
        - test/recipes/default_test.rb
    attributes:
  - name: resource
    provisioner:
      named_run_list: resource
    verifier:
      inspec_tests:
        - test/recipes/default_test.rb
        - test/recipes/resource_test.rb
    attributes:
